# Generated by Django 4.2.18 on 2025-02-13 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('_to', models.IntegerField(null=True)),
                ('sku', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_path', models.TextField(blank=True, null=True)),
                ('date_create', models.TextField(blank=True, null=True)),
                ('cz', models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True)),
                ('qty_per_package', models.IntegerField(blank=True, null=True)),
                ('provider', models.TextField(blank=True, null=True)),
                ('min_shipment', models.IntegerField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_list_delivery_15', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_list_delivery_30', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_list_delivery_45', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_time', models.DateField(blank=True, null=True)),
                ('qty_provider', models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True)),
                ('fulfillment_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'market_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MPRProduct',
            fields=[
                ('code', models.TextField()),
                ('description', models.TextField()),
                ('photo_path', models.TextField()),
                ('provider', models.TextField()),
                ('date_start_sell', models.DateField()),
                ('months_in_the_network', models.IntegerField()),
                ('cz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_qty_sales_6_months', models.IntegerField()),
                ('encode', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mpr_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vid',
            fields=[
                ('vid_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('_to', models.IntegerField(null=True)),
                ('sku', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'vid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
