# Generated by Django 4.2.18 on 2025-03-11 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cz', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена закупки')),
                ('provider', models.CharField(max_length=255, verbose_name='Поставщик')),
                ('min_shipment', models.IntegerField(verbose_name='Минимальная партия')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('qty_per_package', models.IntegerField(verbose_name='Количество в упаковке')),
                ('price_list_delivery_15', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена доставки (15 дней)')),
                ('delivery_time', models.CharField(max_length=50, verbose_name='Срок доставки')),
                ('fulfillment_time', models.CharField(max_length=50, verbose_name='Срок исполнения')),
                ('qty_provider', models.IntegerField(verbose_name='Количество у поставщика')),
                ('price_list_delivery_30', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена доставки (30 дней)')),
                ('price_list_delivery_45', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена доставки (45 дней)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Рыночный товар (запрос)',
                'verbose_name_plural': 'Рыночные товары (запросы)',
            },
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('product_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на товар')),
                ('desired_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Желаемая цена закупки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_by_km', models.BooleanField(default=False, verbose_name='Отработано КМ')),
                ('processed_by_buyer', models.BooleanField(default=False, verbose_name='Отработано Байером')),
            ],
            options={
                'verbose_name': 'Запрос на добавление товара',
                'verbose_name_plural': 'Запросы на добавление товаров',
            },
        ),
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория запроса',
                'verbose_name_plural': 'Категории запросов',
            },
        ),
        migrations.CreateModel(
            name='RequestCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Валюта запроса',
                'verbose_name_plural': 'Валюты запросов',
            },
        ),
        migrations.CreateModel(
            name='RequestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа запроса',
                'verbose_name_plural': 'Группы запросов',
            },
        ),
        migrations.CreateModel(
            name='RequestVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид запроса',
                'verbose_name_plural': 'Виды запросов',
            },
        ),
        migrations.CreateModel(
            name='ProductRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_requests/images/', verbose_name='Фото')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_images', to='product_requests.productrequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Изображение запроса',
                'verbose_name_plural': 'Изображения запросов',
            },
        ),
        migrations.AddField(
            model_name='productrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_requests.requestcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_requests.requestgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_requests', to='product_requests.productrequestimage'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='vid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_requests.requestvid', verbose_name='Вид'),
        ),
        migrations.CreateModel(
            name='MarketProductRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='market_products/images/', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_requests.marketproductrequest', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение рыночного товара (запрос)',
                'verbose_name_plural': 'Изображения рыночных товаров (запросы)',
            },
        ),
        migrations.AddField(
            model_name='marketproductrequest',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_requests.requestcurrency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='marketproductrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_products', to='product_requests.productrequest', verbose_name='Запрос'),
        ),
    ]
